/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/*

    Askhsh 1
*/

#include "ex_calc.h"

// Function to calculate the inner product of two vectors X and Y
int * inner_product_1_svc(InputData *input, struct svc_req *rqstp) {
    // Static variable to store the result
    static int result = 0; 
    
    for (int i = 0; i < input->n; i++) {
        // Calculate the dot product of X and Y
        //input->n gia na vrei ta dedomena apo to struct dhladh kanei access
        result += input->X[i] * input->Y[i];
    }

    return &result;// Return the result as a pointer to an integer
}

// Function to calculate the average values of vectors X and Y
float *avg_values_1_svc(InputData *input, struct svc_req *rqstp) {
    static float result[2]; //static array float
    float sumX = 0, sumY = 0;

    // Calculate the sum of elements in X and Y
    for (int i = 0; i < input->n; i++) {
        // add the sumX,Y
        sumX += input->X[i];
        sumY += input->Y[i];
    }

    result[0] = sumX / input->n; // Calculate the average of X
    result[1] = sumY / input->n; // Calculate the average of Y

    return result;
}

// Function to calculate the product of a real number r and the sum of vectors X and Y
float *vec_product_1_svc(InputData *input, struct svc_req *rqstp) {
    // Allocate memory to store the result using malloc. The size is determined by input->n * the size of float
    float *result = (float*) malloc(input->n * sizeof(float)); //return the pointer from void to float

    // Calculate the product of r and the sum of X and Y
    for (int i = 0; i < input->n; i++) {
        //Calculates the product of X and Y and stores the result in the result array.
        result[i] = input->X[i] * input->Y[i];
    }

    return result;
}
