/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EX_CALC_H_RPCGEN
#define _EX_CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct InputData {
	int n;
	float r;
	float *X;
	float *Y;
};
typedef struct InputData InputData;

#define EX_CALC_PROG 0x23451111
#define EX_CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INNER_PRODUCT 1
extern  int * inner_product_1(InputData *, CLIENT *);
extern  int * inner_product_1_svc(InputData *, struct svc_req *);
#define AVG_VALUES 2
extern  float * avg_values_1(InputData *, CLIENT *);
extern  float * avg_values_1_svc(InputData *, struct svc_req *);
#define VEC_PRODUCT 3
extern  float * vec_product_1(InputData *, CLIENT *);
extern  float * vec_product_1_svc(InputData *, struct svc_req *);
extern int ex_calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INNER_PRODUCT 1
extern  int * inner_product_1();
extern  int * inner_product_1_svc();
#define AVG_VALUES 2
extern  float * avg_values_1();
extern  float * avg_values_1_svc();
#define VEC_PRODUCT 3
extern  float * vec_product_1();
extern  float * vec_product_1_svc();
extern int ex_calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_InputData (XDR *, InputData*);

#else /* K&R C */
extern bool_t xdr_InputData ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EX_CALC_H_RPCGEN */
